-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema traffic_crash
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `traffic_crash` DEFAULT CHARACTER SET utf8;
USE `traffic_crash` ;

-- -----------------------------------------------------
-- Table `traffic_crash`.`PRIM_CONTRIBUTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traffic_crash`.`PRIM_CONTRIBUTORY` (
  `PRIM_CONTRIBUTORY_ID` INT NOT NULL,
  `PRIM_CONTRIBUTORY_CAUSE` TEXT,
  PRIMARY KEY (`PRIM_CONTRIBUTORY_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `traffic_crash`.`crash`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traffic_crash`.`crash` (
  `RD_NO` VARCHAR(45) NOT NULL,
  `CRASH_DATE 1` date,
  `POSTED_SPEED_LIMIT` INT(10) NULL NULL,
  `TRAFFIC_CONTROL_DEVICE` VARCHAR(45),
  `DEVICE_CONDITION` VARCHAR(45),
  `WEATHER_CONDITION` VARCHAR(45),
  `LIGHTING_CONDITION` VARCHAR(45),
  `FIRST_CRASH_TYPE` VARCHAR(45),
  `TRAFFICWAY_TYPE` VARCHAR(45),
  `ALIGNMENT` VARCHAR(45),
  `ROADWAY_SURFACE_COND` VARCHAR(45),
  `CRASH_TYPE` VARCHAR(45),
  `DAMAGE` VARCHAR(45),
  `PRIM_CONTRIBUTORY_ID` INT,
  `SEC_CONTRIBUTORY_CAUSE` VARCHAR(45),
  `STREET_NO` INT(10),
  `STREET_DIRECTION` VARCHAR(45),
  `STREET_NAME` VARCHAR(45),
  `NUM_UNITS` INT(10),
  `MOST_SEVERE_INJURY` VARCHAR(45),
  `INJURIES_TOTAL` VARCHAR(45),
  `INJURIES_FATAL` VARCHAR(45),
  `INJURIES_INCAPACITATING` VARCHAR(45),
  `INJURIES_NON_INCAPACITATING` VARCHAR(45),
  `INJURIES_REPORTED_NOT_EVIDENT` VARCHAR(45),
  `INJURIES_NO_INDICATION` VARCHAR(45),
  `INJURIES_UNKNOWN` VARCHAR(45),
  `CRASH_HOUR` INT(10),
  `CRASH_DAY_OF_WEEK` INT(10),
  `CRASH_MONTH` INT(11) NULL DEFAULT NULL,
  `LATITUDE` DECIMAL(10,8),
  `LONGITUDE` DECIMAL(11,8),
  `ZIPCODE` INT(10),
  PRIMARY KEY (`RD_NO`),
  CONSTRAINT `fk_PRIM_CONTRIBUTORY_crash`
    FOREIGN KEY (`PRIM_CONTRIBUTORY_ID`)
    REFERENCES `traffic_crash`.`PRIM_CONTRIBUTORY` (`PRIM_CONTRIBUTORY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `traffic_crash`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traffic_crash`.`location` (
  `location_id` INT(10) NOT NULL AUTO_INCREMENT,
  `RD_NO` VARCHAR(45) NOT NULL,
  `STREET_NO` INT(10),
  `STREET_DIRECTION` VARCHAR(45),
  `STREET_NAME` VARCHAR(45),
  `LATITUDE` DECIMAL(10,8),
  `LONGITUDE` DECIMAL(11,8),
  PRIMARY KEY (`LOCATION_ID`),
  CONSTRAINT `fk_location_crash1`
    FOREIGN KEY (`RD_NO`)
    REFERENCES `traffic_crash`.`crash` (`RD_NO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 262250
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `traffic_crash`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traffic_crash`.`people` (
  `PERSON_ID`VARCHAR(45) NOT NULL ,
  `PERSON_TYPE` VARCHAR(45),
  `RD_NO` VARCHAR(45) NOT NULL,
  `VEHICLE_ID` INT(10),
  `CRASH_DATE 1` DATE,
  `CITY` VARCHAR(45),
  `STATE` VARCHAR(45),
  `ZIPCODE` VARCHAR(45),
  `SEX` VARCHAR(45),
  `AGE` INT(10),
  `DRIVERS_LICENSE_STATE` VARCHAR(45),
  `DRIVERS_LICENSE_CLASS` VARCHAR(45),
  `INJURY_CLASSIFICATION` VARCHAR(45),
  `DRIVER_ACTION` VARCHAR(45),
  PRIMARY KEY (`PERSON_ID`),
  CONSTRAINT `fk_people_crash`
    FOREIGN KEY (`RD_NO`)
    REFERENCES `traffic_crash`.`crash` (`RD_NO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `traffic_crash`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traffic_crash`.`vehicle` (
  `CRASH_UNIT_ID` INT(20) NOT NULL,
    `RD_NO` VARCHAR(45) NOT NULL,
    `CRASH_DATE 1` DATE NOT NULL,
    `UNIT_NO` INT(20) NOT NULL,
    `UNIT_TYPE` VARCHAR(45),
    `VEHICLE_ID` INT(20),
    `MAKE` VARCHAR(45),
    `MODEL` VARCHAR(45),
    `LIC_PLATE_STATE` VARCHAR(45),
    `VEHICLE_YEAR` INT(20),
    `VEHICLE_DEFECT`  VARCHAR(45),
    `VEHICLE_TYPE`  VARCHAR(45),
    `VEHICLE_USE`  VARCHAR(45),
    `TRAVEL_DIRECTION` VARCHAR(45),
    `MANEUVER` VARCHAR(45),
    `TOWED_I` VARCHAR(45),
    `FIRE_I` VARCHAR(45),
    `OCCUPANT_CNT`INT(10),
    `EXCEED_SPEED_LIMIT_I` VARCHAR(45),
    `FIRST_CONTACT_POINT` VARCHAR(45),
  PRIMARY KEY (`CRASH_UNIT_ID`),
  CONSTRAINT `fk_vehicle_crash1`
    FOREIGN KEY (`RD_NO`)
    REFERENCES `traffic_crash`.`crash` (`RD_NO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

# Insert values into prim_contributory table 
INSERT INTO `traffic_crash`.`PRIM_CONTRIBUTORY`
	(`PRIM_CONTRIBUTORY_ID`,`PRIM_CONTRIBUTORY_CAUSE` ) 
    VALUES 
    ('1','FOLLOWING TOO CLOSELY'),
	('2','FAILING TO YIELD RIGHT-OF-WAY'),
	('3','EQUIPMENT - VEHICLE CONDITION'),
	('4','UNABLE TO DETERMINE'),
	('5','FAILING TO REDUCE SPEED TO AVOID CRASH'),
	('6','PHYSICAL CONDITION OF DRIVER'),
	('7','DRIVING SKILLS/KNOWLEDGE/EXPERIENCE'),
    ('8','IMPROPER LANE USAGE'),
	('9','IMPROPER OVERTAKING/PASSING'),
	('10','IMPROPER BACKING'),
	('11','NOT APPLICABLE'),
	('12','DRIVING ON WRONG SIDE/WRONG WAY'),
	('13','WEATHER'),
	('14','IMPROPER TURNING/NO SIGNAL'),
    ('15','OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER'),
	('16','DISREGARDING STOP SIGN'),
	('17','UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)'),
	('18','DISREGARDING ROAD MARKINGS'),
	('19','DISREGARDING TRAFFIC SIGNALS'),
	('20','RELATED TO BUS STOP'),
	('21','DISTRACTION - FROM OUTSIDE VEHICLE'),
	('22','EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST'),
	('23','VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)'),
	('24','CELL PHONE USE OTHER THAN TEXTING'),
	('25','TEXTING'),
	('26','DISREGARDING OTHER TRAFFIC SIGNS'),
	('27','ANIMAL'),
	('28','DISTRACTION - FROM INSIDE VEHICLE'),
    ('29','ROAD ENGINEERING/SURFACE/MARKING DEFECTS'),
	('30','HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)'),
	('31','ROAD CONSTRUCTION/MAINTENANCE'),
	('32','TURNING RIGHT ON RED'),
	('33','DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)'),
	('34','DISREGARDING YIELD SIGN'),
	('35','MOTORCYCLE ADVANCING LEGALLY ON RED LIGHT'),
    ('36','PASSING STOPPED SCHOOL BUS'),
	('37','BICYCLE ADVANCING LEGALLY ON RED LIGHT'),
	('38','OBSTRUCTED CROSSWALKS'),
	('39','EXCEEDING SAFE SPEED FOR CONDITIONS'),
	('40','EXCEEDING AUTHORIZED SPEED LIMIT');
    
# Insert values into location table 
    INSERT INTO traffic_crash.location (  
    RD_NO, STREET_NO, STREET_DIRECTION, STREET_NAME,
    LATITUDE,LONGITUDE)
(SELECT 
 RD_NO, STREET_NO, STREET_DIRECTION, STREET_NAME, LATITUDE,LONGITUDE
FROM
    traffic_crash.crash);
    
ALTER TABLE crash
  DROP COLUMN STREET_NO,
  DROP COLUMN STREET_DIRECTION,
  DROP COLUMN STREET_NAME,
  DROP COLUMN LATITUDE,
  DROP COLUMN LONGITUDE;